const TRACKER_DATA = [
  {
    "id": "001",
    "fecha": "2026-09-11",
    "jornada": 5,
    "liga": "SP1",
    "partido": "Sevilla vs Valencia",
    "lambda_forma_l": 1.4837,
    "lambda_forma_v": 0.933,
    "lambda_reg_l": 1.1851,
    "lambda_reg_v": 0.9993,
    "lambda_base_l": 1.2747,
    "lambda_base_v": 0.9794,
    "lambda_final_l": 1.3042,
    "lambda_final_v": 0.9499,
    "lambda_shadow_l": 1.227,
    "lambda_shadow_v": 0.8122,
    "lambda_corners": 8.286,
    "ratio": 1.3729866301715972,
    "visit_dominante": "False",
    "variables_activas": "V#2(V:0.95) - V#3(L:0.98) - V#4(L:0.96) - V#4(V:0.90)",
    "variables": {
      "v1": {
        "factor_local": 1.0,
        "factor_visit": 1.0,
        "activa": false,
        "activa_local": false,
        "activa_visit": false,
        "detalle_local": "--",
        "detalle_visit": "--",
        "detalle": "Ambos necesitan >=20 PJ (local:4, visit:4)"
      },
      "v2": {
        "factor_local": 1.0,
        "factor_visit": 0.95,
        "activa_local": false,
        "activa_visit": true,
        "detalle_local": "Rank 7, margen 5pts -- fuera de riesgo",
        "detalle_visit": "Rank 20, margen -1pts sobre zona desc"
      },
      "v3": {
        "factor_local": 0.98,
        "activa": true,
        "n_partidos": 20,
        "GpG_casa": 1.3,
        "GpG_liga": 1.5,
        "hs": -0.2,
        "muestra_completa": true,
        "detalle": "hs=-0.20 (20 ptdos)"
      },
      "v4": {
        "factor_local": 0.96,
        "factor_visit": 0.9,
        "activa_local": true,
        "activa_visit": true,
        "bajas_local": 2,
        "bajas_visit": 8
      },
      "v5": {
        "factor_local": 1.0,
        "factor_visit": 1.0,
        "activa_local": false,
        "activa_visit": false
      },
      "v6": {
        "factor_local": 1.0,
        "factor_visit": 1.0,
        "activa": false
      },
      "v7": {
        "skip": false,
        "activa_local": false,
        "activa_visit": false,
        "detalle": "Sin DT nuevo"
      },
      "v8": {
        "activa": false,
        "anulado_derby": false,
        "detalle": "Inactiva"
      }
    },
    "confianza": "ALTA",
    "notas": "",
    "resultado_partido": "1-0",
    "goles_esperados": "2.25",
    "apuestas": [
      {
        "tipo": "PICK",
        "mercado": "over15",
        "linea": null,
        "etiqueta": "Over 1.5",
        "cuota": 1.45,
        "prob": 70.1,
        "ev_pct": 1.6,
        "estado": "PERDIDA",
        "pl": -1.0
      }
    ],
    "watchlist": [
      {
        "mercado": "empate",
        "linea": null,
        "etiqueta": "Empate",
        "cuota": 3.25,
        "prob": 31.5,
        "ev_pct": 2.4,
        "regla_1x2_no_pick": true,
        "acerto": false
      },
      {
        "mercado": "do1x",
        "linea": null,
        "etiqueta": "DO Sevilla o Empate",
        "cuota": 1.28,
        "prob": 74.8,
        "ev_pct": -4.3,
        "cuota_justa": 1.42,
        "cuota_segura": 1.57,
        "acierto_hist": 70.6,
        "n_hist": 194,
        "acerto": true
      },
      {
        "mercado": "over25",
        "linea": null,
        "etiqueta": "Over 2.5",
        "cuota": 2.32,
        "prob": 41.7,
        "ev_pct": -3.3,
        "acerto": false
      },
      {
        "mercado": "under35",
        "linea": null,
        "etiqueta": "Under 3.5",
        "cuota": 1.23,
        "prob": 80.9,
        "ev_pct": -0.5,
        "acerto": true
      },
      {
        "mercado": "under45",
        "linea": null,
        "etiqueta": "Under 4.5",
        "cuota": 1.08,
        "prob": 92.2,
        "ev_pct": -0.4,
        "acerto": true
      },
      {
        "mercado": "btts",
        "linea": null,
        "etiqueta": "BTTS",
        "cuota": 2.0,
        "prob": 51.3,
        "ev_pct": 2.6,
        "filtro_edge": "dPlatt=6.6pp",
        "acerto": false
      },
      {
        "mercado": "over05_local",
        "linea": null,
        "etiqueta": "Over 0.5 Sevilla",
        "cuota": 1.29,
        "prob": 74.6,
        "ev_pct": -3.8,
        "cuota_justa": 1.38,
        "cuota_segura": 1.51,
        "acierto_hist": 72.3,
        "n_hist": 238,
        "acerto": true
      },
      {
        "mercado": "over05_visit",
        "linea": null,
        "etiqueta": "Over 0.5 Valencia",
        "cuota": 1.57,
        "prob": 61.3,
        "ev_pct": -3.8,
        "cuota_justa": 1.59,
        "cuota_segura": 1.77,
        "acierto_hist": 62.9,
        "n_hist": 224,
        "acerto": false
      },
      {
        "mercado": "hcp2_des",
        "linea": null,
        "etiqueta": "HCP +2 Valencia",
        "cuota": 1.25,
        "prob": 79.4,
        "ev_pct": -0.7,
        "acerto": true
      },
      {
        "mercado": "hcp3_des",
        "linea": null,
        "etiqueta": "HCP +3 Valencia",
        "cuota": 1.07,
        "prob": 92.6,
        "ev_pct": -0.9,
        "acerto": true
      },
      {
        "mercado": "corners65",
        "linea": null,
        "etiqueta": "Over 6.5 corners",
        "cuota": 1.28,
        "prob": 82.0,
        "ev_pct": 5.0,
        "filtro_edge": "a=0.08 (Platt no discrimina)",
        "acerto": true
      },
      {
        "mercado": "local_corners_equipo",
        "linea": 2.5,
        "etiqueta": "Sevilla Corners equipo Over 2.5",
        "cuota": 1.13,
        "prob": 81.9,
        "ev_pct": -7.5,
        "tipo": "POR_EQUIPO",
        "acerto": true
      },
      {
        "mercado": "local_corners_equipo",
        "linea": 3.5,
        "etiqueta": "Sevilla Corners equipo Over 3.5",
        "cuota": 1.32,
        "prob": 67.6,
        "ev_pct": -10.8,
        "tipo": "POR_EQUIPO",
        "cuota_justa": 1.44,
        "cuota_segura": 1.56,
        "acierto_hist": 69.2,
        "n_hist": 325,
        "acerto": true
      },
      {
        "mercado": "local_remates_puerta",
        "linea": 3.5,
        "etiqueta": "Sevilla Remates a puerta Over 3.5",
        "cuota": 1.5,
        "prob": 65.1,
        "ev_pct": -2.4,
        "tipo": "POR_EQUIPO",
        "cuota_justa": 1.52,
        "cuota_segura": 1.68,
        "acierto_hist": 65.7,
        "n_hist": 236,
        "acerto": true
      },
      {
        "mercado": "under45+hcp2_visit",
        "linea": null,
        "etiqueta": "Under 4.5 + HCP +2 V",
        "cuota": 1.34,
        "prob": 74.4,
        "ev_pct": -0.3,
        "tipo": "COMBINADA",
        "patas": [
          "under45",
          "hcp2_visit"
        ],
        "lift": 1.038,
        "cuota_justa": 1.35,
        "cuota_segura": 1.46,
        "acierto_hist": 73.8,
        "n_hist": 298,
        "acerto": true
      },
      {
        "mercado": "under35+hcp2_visit",
        "linea": null,
        "etiqueta": "Under 3.5 + HCP +2 V",
        "cuota": 1.47,
        "prob": 68.0,
        "ev_pct": 0.0,
        "tipo": "COMBINADA",
        "patas": [
          "under35",
          "hcp2_visit"
        ],
        "lift": 1.106,
        "cuota_justa": 1.48,
        "cuota_segura": 1.62,
        "acierto_hist": 67.7,
        "n_hist": 269,
        "acerto": true
      },
      {
        "mercado": "over15+over05_local",
        "linea": null,
        "etiqueta": "Over 1.5 + Over 0.5 L",
        "cuota": 1.53,
        "prob": 59.2,
        "ev_pct": -9.5,
        "tipo": "COMBINADA",
        "patas": [
          "over15",
          "over05_local"
        ],
        "lift": 1.158,
        "cuota_justa": 1.75,
        "cuota_segura": 1.98,
        "acierto_hist": 57.1,
        "n_hist": 210,
        "acerto": false
      },
      {
        "mercado": "under35+hcp2_local",
        "linea": null,
        "etiqueta": "Under 3.5 + HCP +2 L",
        "cuota": 1.3,
        "prob": 74.6,
        "ev_pct": -3.0,
        "tipo": "COMBINADA",
        "patas": [
          "under35",
          "hcp2_local"
        ],
        "lift": 1.053,
        "cuota_justa": 1.37,
        "cuota_segura": 1.5,
        "acierto_hist": 73.2,
        "n_hist": 205,
        "acerto": true
      }
    ],
    "mercados_snapshot": {
      "victoria_local": 44.7,
      "empate": 31.5,
      "victoria_visit": 25.3,
      "do1x": 74.8,
      "dox2": 55.3,
      "over15": 70.1,
      "over25": 41.7,
      "under25": 58.3,
      "over35": 19.1,
      "under35": 80.9,
      "under45": 92.2,
      "btts": 51.3,
      "over05_local": 74.6,
      "over05_visit": 61.3,
      "hcp2_des": 79.4,
      "hcp3_des": 92.6,
      "corners65": 82.0,
      "local_remates_over7.5": 94.0,
      "local_remates_over8.5": 90.2,
      "local_remates_over9.5": 85.2,
      "local_remates_over10.5": 79.0,
      "local_remates_over11.5": 72.0,
      "local_remates_over12.5": 64.2,
      "local_remates_over13.5": 56.2,
      "local_remates_over14.5": 48.1,
      "local_remates_over15.5": 40.4,
      "local_remates_puerta_over1.5": 93.1,
      "local_remates_puerta_over2.5": 81.6,
      "local_remates_puerta_over3.5": 65.1,
      "local_remates_puerta_over4.5": 47.1,
      "local_remates_puerta_over5.5": 30.8,
      "local_remates_puerta_over6.5": 18.4,
      "local_corners_equipo_over2.5": 81.9,
      "local_corners_equipo_over3.5": 67.6,
      "local_corners_equipo_over4.5": 52.2,
      "local_corners_equipo_over5.5": 37.8,
      "local_corners_equipo_over6.5": 25.8,
      "local_corners_equipo_over7.5": 16.7,
      "visit_remates_over7.5": 59.6,
      "visit_remates_over8.5": 48.0,
      "visit_remates_over9.5": 37.1,
      "visit_remates_over10.5": 27.6,
      "visit_remates_over11.5": 19.8,
      "visit_remates_over12.5": 13.7,
      "visit_remates_over13.5": 9.2,
      "visit_remates_over14.5": 6.0,
      "visit_remates_over15.5": 3.8,
      "visit_remates_puerta_over1.5": 78.0,
      "visit_remates_puerta_over2.5": 55.5,
      "visit_remates_puerta_over3.5": 33.9,
      "visit_remates_puerta_over4.5": 18.0,
      "visit_remates_puerta_over5.5": 8.5,
      "visit_remates_puerta_over6.5": 3.6,
      "visit_corners_equipo_over2.5": 57.5,
      "visit_corners_equipo_over3.5": 37.9,
      "visit_corners_equipo_over4.5": 22.6,
      "visit_corners_equipo_over5.5": 12.4,
      "visit_corners_equipo_over6.5": 6.3,
      "visit_corners_equipo_over7.5": 3.0
    },
    "cruces_validados": [
      {
        "mercado": "do1x",
        "etiqueta": "DO L o Empate",
        "cuota": 1.28,
        "justa": 1.42,
        "segura": 1.57,
        "hist": 70.6,
        "n": 194,
        "cruza": false,
        "cruza_segura": false,
        "acerto": true
      },
      {
        "mercado": "over05_local",
        "etiqueta": "Over 0.5 L",
        "cuota": 1.29,
        "justa": 1.38,
        "segura": 1.51,
        "hist": 72.3,
        "n": 238,
        "cruza": false,
        "cruza_segura": false,
        "acerto": true
      },
      {
        "mercado": "over05_visit",
        "etiqueta": "Over 0.5 V",
        "cuota": 1.57,
        "justa": 1.59,
        "segura": 1.77,
        "hist": 62.9,
        "n": 224,
        "cruza": false,
        "cruza_segura": false,
        "acerto": false
      },
      {
        "mercado": "local_corners_equipo_over3.5",
        "etiqueta": "Sevilla Corners Over 3.5",
        "cuota": 1.32,
        "justa": 1.44,
        "segura": 1.56,
        "hist": 69.2,
        "n": 325,
        "cruza": false,
        "cruza_segura": false,
        "acerto": true
      },
      {
        "mercado": "local_remates_puerta_over3.5",
        "etiqueta": "Sevilla Remates a puerta Over 3.5",
        "cuota": 1.5,
        "justa": 1.52,
        "segura": 1.68,
        "hist": 65.7,
        "n": 236,
        "cruza": false,
        "cruza_segura": false,
        "acerto": true
      },
      {
        "mercado": "under45+hcp2_visit",
        "etiqueta": "Under 4.5 + HCP +2 V",
        "cuota": 1.34,
        "justa": 1.35,
        "segura": 1.46,
        "hist": 73.8,
        "n": 298,
        "cruza": false,
        "cruza_segura": false,
        "acerto": true
      },
      {
        "mercado": "under35+hcp2_visit",
        "etiqueta": "Under 3.5 + HCP +2 V",
        "cuota": 1.47,
        "justa": 1.48,
        "segura": 1.62,
        "hist": 67.7,
        "n": 269,
        "cruza": false,
        "cruza_segura": false,
        "acerto": true
      },
      {
        "mercado": "over15+over05_local",
        "etiqueta": "Over 1.5 + Over 0.5 L",
        "cuota": 1.53,
        "justa": 1.75,
        "segura": 1.98,
        "hist": 57.1,
        "n": 210,
        "cruza": false,
        "cruza_segura": false,
        "acerto": false
      },
      {
        "mercado": "under35+hcp2_local",
        "etiqueta": "Under 3.5 + HCP +2 L",
        "cuota": 1.3,
        "justa": 1.37,
        "segura": 1.5,
        "hist": 73.2,
        "n": 205,
        "cruza": false,
        "cruza_segura": false,
        "acerto": true
      }
    ],
    "validadas": [
      {
        "mercado": "local_corners_equipo_over3.5",
        "etiqueta": "Sevilla Corners Over 3.5",
        "tipo": "por equipo",
        "p": 0.6763,
        "cuota_justa": 1.44,
        "cuota_segura": 1.56,
        "acierto_hist": 69.2,
        "n_hist": 325,
        "cotizada": true
      },
      {
        "mercado": "under45+hcp2_visit",
        "etiqueta": "Under 4.5 + HCP +2 V",
        "tipo": "COMBINADA",
        "p": 0.7439,
        "cuota_justa": 1.35,
        "cuota_segura": 1.46,
        "acierto_hist": 73.8,
        "n_hist": 298,
        "cotizada": true
      },
      {
        "mercado": "over15+hcp3_local",
        "etiqueta": "Over 1.5 + HCP +3 L",
        "tipo": "COMBINADA",
        "p": 0.6327,
        "cuota_justa": 1.56,
        "cuota_segura": 1.71,
        "acierto_hist": 64.1,
        "n_hist": 284,
        "cotizada": false
      },
      {
        "mercado": "under35+hcp2_visit",
        "etiqueta": "Under 3.5 + HCP +2 V",
        "tipo": "COMBINADA",
        "p": 0.6805,
        "cuota_justa": 1.48,
        "cuota_segura": 1.62,
        "acierto_hist": 67.7,
        "n_hist": 269,
        "cotizada": true
      },
      {
        "mercado": "over05_local",
        "etiqueta": "Over 0.5 L",
        "tipo": "simple",
        "p": 0.7458,
        "cuota_justa": 1.38,
        "cuota_segura": 1.51,
        "acierto_hist": 72.3,
        "n_hist": 238,
        "cotizada": true
      },
      {
        "mercado": "hcp2_visit",
        "etiqueta": "HCP +2 V",
        "tipo": "simple",
        "p": 0.794,
        "cuota_justa": 1.26,
        "cuota_segura": 1.36,
        "acierto_hist": 79.3,
        "n_hist": 237,
        "cotizada": false
      },
      {
        "mercado": "local_remates_puerta_over3.5",
        "etiqueta": "Sevilla Remates a puerta Over 3.5",
        "tipo": "por equipo",
        "p": 0.6512,
        "cuota_justa": 1.52,
        "cuota_segura": 1.68,
        "acierto_hist": 65.7,
        "n_hist": 236,
        "cotizada": true
      },
      {
        "mercado": "local_remates_over10.5",
        "etiqueta": "Sevilla Remates Over 10.5",
        "tipo": "por equipo",
        "p": 0.7905,
        "cuota_justa": 1.29,
        "cuota_segura": 1.4,
        "acierto_hist": 77.3,
        "n_hist": 233,
        "cotizada": false
      },
      {
        "mercado": "dox2+hcp3_local",
        "etiqueta": "DO Empate o V + HCP +3 L",
        "tipo": "COMBINADA",
        "p": 0.5271,
        "cuota_justa": 1.93,
        "cuota_segura": 2.21,
        "acierto_hist": 51.7,
        "n_hist": 230,
        "cotizada": false
      },
      {
        "mercado": "local_corners_equipo_over2.5+local_remates_over10.5",
        "etiqueta": "L Corners Over 2.5 + L Remates Over 10.5",
        "tipo": "COMBINADA",
        "p": 0.6978,
        "cuota_justa": 1.42,
        "cuota_segura": 1.56,
        "acierto_hist": 70.5,
        "n_hist": 227,
        "cotizada": false
      },
      {
        "mercado": "local_remates_puerta_over3.5+over05_local",
        "etiqueta": "L Remates a puerta Over 3.5 + Over 0.5 L",
        "tipo": "COMBINADA",
        "p": 0.5537,
        "cuota_justa": 1.65,
        "cuota_segura": 1.85,
        "acierto_hist": 60.4,
        "n_hist": 225,
        "cotizada": false
      },
      {
        "mercado": "over05_visit",
        "etiqueta": "Over 0.5 V",
        "tipo": "simple",
        "p": 0.6132,
        "cuota_justa": 1.59,
        "cuota_segura": 1.77,
        "acierto_hist": 62.9,
        "n_hist": 224,
        "cotizada": true
      },
      {
        "mercado": "local_corners_equipo_over2.5+local_remates_over9.5",
        "etiqueta": "L Corners Over 2.5 + L Remates Over 9.5",
        "tipo": "COMBINADA",
        "p": 0.7441,
        "cuota_justa": 1.34,
        "cuota_segura": 1.46,
        "acierto_hist": 74.6,
        "n_hist": 213,
        "cotizada": false
      },
      {
        "mercado": "over15+over05_local",
        "etiqueta": "Over 1.5 + Over 0.5 L",
        "tipo": "COMBINADA",
        "p": 0.5917,
        "cuota_justa": 1.75,
        "cuota_segura": 1.98,
        "acierto_hist": 57.1,
        "n_hist": 210,
        "cotizada": true
      },
      {
        "mercado": "local_corners_equipo_over4.5+local_remates_over9.5",
        "etiqueta": "L Corners Over 4.5 + L Remates Over 9.5",
        "tipo": "COMBINADA",
        "p": 0.503,
        "cuota_justa": 1.84,
        "cuota_segura": 2.1,
        "acierto_hist": 54.3,
        "n_hist": 208,
        "cotizada": false
      },
      {
        "mercado": "under35+hcp2_local",
        "etiqueta": "Under 3.5 + HCP +2 L",
        "tipo": "COMBINADA",
        "p": 0.7463,
        "cuota_justa": 1.37,
        "cuota_segura": 1.5,
        "acierto_hist": 73.2,
        "n_hist": 205,
        "cotizada": true
      },
      {
        "mercado": "local_remates_puerta_over2.5+over05_local",
        "etiqueta": "L Remates a puerta Over 2.5 + Over 0.5 L",
        "tipo": "COMBINADA",
        "p": 0.6607,
        "cuota_justa": 1.5,
        "cuota_segura": 1.67,
        "acierto_hist": 66.7,
        "n_hist": 204,
        "cotizada": false
      },
      {
        "mercado": "local_remates_over8.5+local_remates_puerta_over2.5",
        "etiqueta": "L Remates Over 8.5 + L Remates a puerta Over 2.5",
        "tipo": "COMBINADA",
        "p": 0.7994,
        "cuota_justa": 1.33,
        "cuota_segura": 1.45,
        "acierto_hist": 75.2,
        "n_hist": 202,
        "cotizada": false
      },
      {
        "mercado": "do1x",
        "etiqueta": "DO L o Empate",
        "tipo": "simple",
        "p": 0.7475,
        "cuota_justa": 1.42,
        "cuota_segura": 1.57,
        "acierto_hist": 70.6,
        "n_hist": 194,
        "cotizada": true
      },
      {
        "mercado": "local_remates_over11.5+local_remates_puerta_over3.5",
        "etiqueta": "L Remates Over 11.5 + L Remates a puerta Over 3.5",
        "tipo": "COMBINADA",
        "p": 0.5574,
        "cuota_justa": 1.75,
        "cuota_segura": 2.0,
        "acierto_hist": 57.1,
        "n_hist": 189,
        "cotizada": false
      },
      {
        "mercado": "local_remates_over9.5+local_remates_puerta_over2.5",
        "etiqueta": "L Remates Over 9.5 + L Remates a puerta Over 2.5",
        "tipo": "COMBINADA",
        "p": 0.7643,
        "cuota_justa": 1.3,
        "cuota_segura": 1.44,
        "acierto_hist": 76.6,
        "n_hist": 167,
        "cotizada": false
      },
      {
        "mercado": "under25+hcp2_visit",
        "etiqueta": "Under 2.5 + HCP +2 V",
        "tipo": "COMBINADA",
        "p": 0.519,
        "cuota_justa": 1.99,
        "cuota_segura": 2.34,
        "acierto_hist": 50.3,
        "n_hist": 163,
        "cotizada": false
      },
      {
        "mercado": "local_remates_over10.5+local_remates_puerta_over2.5",
        "etiqueta": "L Remates Over 10.5 + L Remates a puerta Over 2.5",
        "tipo": "COMBINADA",
        "p": 0.7156,
        "cuota_justa": 1.41,
        "cuota_segura": 1.57,
        "acierto_hist": 71.2,
        "n_hist": 156,
        "cotizada": false
      },
      {
        "mercado": "local_corners_equipo_over2.5+local_remates_over12.5",
        "etiqueta": "L Corners Over 2.5 + L Remates Over 12.5",
        "tipo": "COMBINADA",
        "p": 0.5643,
        "cuota_justa": 1.76,
        "cuota_segura": 2.04,
        "acierto_hist": 56.8,
        "n_hist": 155,
        "cotizada": false
      },
      {
        "mercado": "do1x+local_remates_puerta_over2.5",
        "etiqueta": "DO L o Empate + L Remates a puerta Over 2.5",
        "tipo": "COMBINADA",
        "p": 0.6534,
        "cuota_justa": 1.5,
        "cuota_segura": 1.7,
        "acierto_hist": 66.7,
        "n_hist": 150,
        "cotizada": false
      }
    ],
    "stats_reales": null,
    "snapshot_resultados": {
      "victoria_local": true,
      "empate": false,
      "victoria_visit": false,
      "do1x": true,
      "dox2": false,
      "over15": false,
      "over25": false,
      "under25": true,
      "over35": false,
      "under35": true,
      "under45": true,
      "btts": false,
      "over05_local": true,
      "over05_visit": false,
      "hcp2_des": true,
      "hcp3_des": true,
      "corners65": true,
      "local_remates_puerta_over1.5": true,
      "local_remates_puerta_over2.5": true,
      "local_remates_puerta_over3.5": true,
      "local_remates_puerta_over4.5": false,
      "local_remates_puerta_over5.5": false,
      "local_remates_puerta_over6.5": false,
      "local_corners_equipo_over2.5": true,
      "local_corners_equipo_over3.5": true,
      "local_corners_equipo_over4.5": true,
      "local_corners_equipo_over5.5": true,
      "local_corners_equipo_over6.5": false,
      "local_corners_equipo_over7.5": false,
      "visit_corners_equipo_over2.5": true,
      "visit_corners_equipo_over3.5": true,
      "visit_corners_equipo_over4.5": false,
      "visit_corners_equipo_over5.5": false,
      "visit_corners_equipo_over6.5": false,
      "visit_corners_equipo_over7.5": false
    }
  },
  {
    "id": "002",
    "fecha": "2026-09-12",
    "jornada": 5,
    "liga": "SP1",
    "partido": "Athletic Club vs Elche",
    "lambda_forma_l": 1.656,
    "lambda_forma_v": 1.5805,
    "lambda_reg_l": 1.9566,
    "lambda_reg_v": 0.8858,
    "lambda_base_l": 1.8664,
    "lambda_base_v": 1.0942,
    "lambda_final_l": 1.9436,
    "lambda_final_v": 1.017,
    "lambda_shadow_l": 1.7443,
    "lambda_shadow_v": 0.9661,
    "lambda_corners": 11.714,
    "ratio": 1.9111111111111112,
    "visit_dominante": "False",
    "variables_activas": "V#2(V:0.95) - V#3(L:0.96) - V#4(L:0.93)",
    "variables": {
      "v1": {
        "factor_local": 1.0,
        "factor_visit": 1.0,
        "activa": false,
        "activa_local": false,
        "activa_visit": false,
        "detalle_local": "--",
        "detalle_visit": "--",
        "detalle": "Ambos necesitan >=20 PJ (local:4, visit:4)"
      },
      "v2": {
        "factor_local": 1.0,
        "factor_visit": 0.95,
        "activa_local": false,
        "activa_visit": true,
        "detalle_local": "Rank 10, margen 4pts -- fuera de riesgo",
        "detalle_visit": "Rank 19, margen -1pts sobre zona desc"
      },
      "v3": {
        "factor_local": 0.965,
        "activa": true,
        "n_partidos": 20,
        "GpG_casa": 1.15,
        "GpG_liga": 1.5,
        "hs": -0.35,
        "muestra_completa": true,
        "detalle": "hs=-0.35 (20 ptdos)"
      },
      "v4": {
        "factor_local": 0.93,
        "factor_visit": 1.0,
        "activa_local": true,
        "activa_visit": false,
        "bajas_local": 4,
        "bajas_visit": 1
      },
      "v5": {
        "factor_local": 1.0,
        "factor_visit": 1.0,
        "activa_local": false,
        "activa_visit": false
      },
      "v6": {
        "factor_local": 1.0,
        "factor_visit": 1.0,
        "activa": false
      },
      "v7": {
        "skip": false,
        "activa_local": false,
        "activa_visit": false,
        "detalle": "Sin DT nuevo"
      },
      "v8": {
        "activa": false,
        "anulado_derby": false,
        "detalle": "Inactiva"
      }
    },
    "confianza": "ALTA",
    "notas": "",
    "resultado_partido": null,
    "goles_esperados": "2.96",
    "apuestas": [
      {
        "tipo": "PICK",
        "mercado": "btts",
        "linea": null,
        "etiqueta": "BTTS",
        "cuota": 1.9,
        "prob": 57.4,
        "ev_pct": 9.1,
        "estado": "PENDIENTE",
        "pl": null,
        "cuota_justa": 1.7,
        "cuota_segura": 1.83,
        "acierto_hist": 58.7,
        "n_hist": 606
      },
      {
        "tipo": "PICK",
        "mercado": "over05_visit",
        "linea": null,
        "etiqueta": "Over 0.5 Elche",
        "cuota": 1.7,
        "prob": 63.8,
        "ev_pct": 8.5,
        "estado": "PENDIENTE",
        "pl": null,
        "cuota_justa": 1.59,
        "cuota_segura": 1.77,
        "acierto_hist": 62.9,
        "n_hist": 224
      },
      {
        "tipo": "COMBO",
        "mercado": "over15+hcp3_visit",
        "etiqueta": "Over 1.5 + HCP +3 V",
        "cuota": 1.67,
        "prob": 62.5,
        "ev_pct": 4.3,
        "estado": "PENDIENTE",
        "pl": null,
        "patas": [
          "over15",
          "hcp3_visit"
        ],
        "promovida_combinada": true,
        "nivel_cruce": "justa",
        "cuota_justa": 1.55,
        "cuota_segura": 1.68,
        "acierto_hist": 64.5,
        "n_hist": 375
      }
    ],
    "watchlist": [
      {
        "mercado": "empate",
        "linea": null,
        "etiqueta": "Empate",
        "cuota": 4.65,
        "prob": 23.9,
        "ev_pct": 11.1,
        "regla_1x2_no_pick": true
      },
      {
        "mercado": "over15",
        "linea": null,
        "etiqueta": "Over 1.5",
        "cuota": 1.23,
        "prob": 80.7,
        "ev_pct": -0.7
      },
      {
        "mercado": "over25",
        "linea": null,
        "etiqueta": "Over 2.5",
        "cuota": 1.7,
        "prob": 57.3,
        "ev_pct": -2.6,
        "cuota_justa": 1.82,
        "cuota_segura": 2.0,
        "acierto_hist": 55.1,
        "n_hist": 354
      },
      {
        "mercado": "under35",
        "linea": null,
        "etiqueta": "Under 3.5",
        "cuota": 1.47,
        "prob": 65.6,
        "ev_pct": -3.6,
        "cuota_justa": 1.51,
        "cuota_segura": 1.64,
        "acierto_hist": 66.3,
        "n_hist": 341
      },
      {
        "mercado": "under45",
        "linea": null,
        "etiqueta": "Under 4.5",
        "cuota": 1.19,
        "prob": 82.2,
        "ev_pct": -2.2
      },
      {
        "mercado": "over05_local",
        "linea": null,
        "etiqueta": "Over 0.5 Athletic Club",
        "cuota": 1.1,
        "prob": 87.6,
        "ev_pct": -3.6
      },
      {
        "mercado": "corners65",
        "linea": null,
        "etiqueta": "Over 6.5 corners",
        "cuota": 1.15,
        "prob": 84.2,
        "ev_pct": -3.2
      },
      {
        "mercado": "local_corners_equipo",
        "linea": 3.5,
        "etiqueta": "Athletic Club Corners equipo Over 3.5",
        "cuota": 1.28,
        "prob": 67.3,
        "ev_pct": -13.9,
        "tipo": "POR_EQUIPO",
        "cuota_justa": 1.44,
        "cuota_segura": 1.56,
        "acierto_hist": 69.2,
        "n_hist": 325
      },
      {
        "mercado": "visit_corners_equipo",
        "linea": 3.5,
        "etiqueta": "Elche Corners equipo Over 3.5",
        "cuota": 1.47,
        "prob": 68.8,
        "ev_pct": 1.1,
        "tipo": "POR_EQUIPO",
        "cuota_justa": 1.49,
        "cuota_segura": 1.68,
        "acierto_hist": 67.3,
        "n_hist": 159
      },
      {
        "mercado": "visit_remates_puerta",
        "linea": 3.5,
        "etiqueta": "Elche Remates a puerta Over 3.5",
        "cuota": 2.57,
        "prob": 57.5,
        "ev_pct": 47.8,
        "tipo": "POR_EQUIPO",
        "cuota_justa": 1.74,
        "cuota_segura": 2.0,
        "acierto_hist": 57.6,
        "n_hist": 172
      },
      {
        "mercado": "over15+over05_local",
        "linea": null,
        "etiqueta": "Over 1.5 + Over 0.5 L",
        "cuota": 1.24,
        "prob": 75.6,
        "ev_pct": -6.2,
        "tipo": "COMBINADA",
        "patas": [
          "over15",
          "over05_local"
        ],
        "lift": 1.158,
        "cuota_justa": 1.27,
        "cuota_segura": 1.39,
        "acierto_hist": 78.6,
        "n_hist": 182
      },
      {
        "mercado": "do1x+under35",
        "linea": null,
        "etiqueta": "DO L o Empate + Under 3.5",
        "cuota": 1.67,
        "prob": 51.5,
        "ev_pct": -13.9,
        "tipo": "COMBINADA",
        "patas": [
          "do1x",
          "under35"
        ],
        "lift": 1.009,
        "cuota_justa": 1.98,
        "cuota_segura": 2.24,
        "acierto_hist": 50.5,
        "n_hist": 277
      }
    ],
    "mercados_snapshot": {
      "victoria_local": 59.0,
      "empate": 23.9,
      "victoria_visit": 16.8,
      "do1x": 83.2,
      "dox2": 41.0,
      "over15": 80.7,
      "over25": 57.3,
      "under25": 42.7,
      "over35": 34.4,
      "under35": 65.6,
      "under45": 82.2,
      "btts": 57.4,
      "over05_local": 87.6,
      "over05_visit": 63.8,
      "hcp2_des": 64.9,
      "hcp3_des": 83.0,
      "corners65": 84.2,
      "local_remates_over7.5": 89.5,
      "local_remates_over8.5": 83.8,
      "local_remates_over9.5": 76.8,
      "local_remates_over10.5": 68.8,
      "local_remates_over11.5": 60.2,
      "local_remates_over12.5": 51.4,
      "local_remates_over13.5": 42.9,
      "local_remates_over14.5": 34.9,
      "local_remates_over15.5": 27.8,
      "local_remates_puerta_over1.5": 94.6,
      "local_remates_puerta_over2.5": 84.9,
      "local_remates_puerta_over3.5": 70.0,
      "local_remates_puerta_over4.5": 52.7,
      "local_remates_puerta_over5.5": 36.2,
      "local_remates_puerta_over6.5": 22.8,
      "local_corners_equipo_over2.5": 81.6,
      "local_corners_equipo_over3.5": 67.3,
      "local_corners_equipo_over4.5": 51.7,
      "local_corners_equipo_over5.5": 37.3,
      "local_corners_equipo_over6.5": 25.4,
      "local_corners_equipo_over7.5": 16.4,
      "visit_remates_over7.5": 81.8,
      "visit_remates_over8.5": 73.6,
      "visit_remates_over9.5": 64.4,
      "visit_remates_over10.5": 54.7,
      "visit_remates_over11.5": 45.2,
      "visit_remates_over12.5": 36.3,
      "visit_remates_over13.5": 28.3,
      "visit_remates_over14.5": 21.5,
      "visit_remates_over15.5": 16.0,
      "visit_remates_puerta_over1.5": 90.5,
      "visit_remates_puerta_over2.5": 76.1,
      "visit_remates_puerta_over3.5": 57.5,
      "visit_remates_puerta_over4.5": 38.9,
      "visit_remates_puerta_over5.5": 23.7,
      "visit_remates_puerta_over6.5": 13.1,
      "visit_corners_equipo_over2.5": 82.7,
      "visit_corners_equipo_over3.5": 68.8,
      "visit_corners_equipo_over4.5": 53.5,
      "visit_corners_equipo_over5.5": 39.1,
      "visit_corners_equipo_over6.5": 27.0,
      "visit_corners_equipo_over7.5": 17.7
    },
    "cruces_validados": [
      {
        "mercado": "over25",
        "etiqueta": "Over 2.5",
        "cuota": 1.7,
        "justa": 1.82,
        "segura": 2.0,
        "hist": 55.1,
        "n": 354,
        "cruza": false,
        "cruza_segura": false
      },
      {
        "mercado": "under35",
        "etiqueta": "Under 3.5",
        "cuota": 1.47,
        "justa": 1.51,
        "segura": 1.64,
        "hist": 66.3,
        "n": 341,
        "cruza": false,
        "cruza_segura": false
      },
      {
        "mercado": "btts",
        "etiqueta": "BTTS",
        "cuota": 1.9,
        "justa": 1.7,
        "segura": 1.83,
        "hist": 58.7,
        "n": 606,
        "cruza": true,
        "cruza_segura": true
      },
      {
        "mercado": "over05_visit",
        "etiqueta": "Over 0.5 V",
        "cuota": 1.7,
        "justa": 1.59,
        "segura": 1.77,
        "hist": 62.9,
        "n": 224,
        "cruza": true,
        "cruza_segura": false
      },
      {
        "mercado": "local_corners_equipo_over3.5",
        "etiqueta": "Athletic Club Corners Over 3.5",
        "cuota": 1.28,
        "justa": 1.44,
        "segura": 1.56,
        "hist": 69.2,
        "n": 325,
        "cruza": false,
        "cruza_segura": false
      },
      {
        "mercado": "visit_corners_equipo_over3.5",
        "etiqueta": "Elche Corners Over 3.5",
        "cuota": 1.47,
        "justa": 1.49,
        "segura": 1.68,
        "hist": 67.3,
        "n": 159,
        "cruza": false,
        "cruza_segura": false
      },
      {
        "mercado": "visit_remates_puerta_over3.5",
        "etiqueta": "Elche Remates a puerta Over 3.5",
        "cuota": 2.57,
        "justa": 1.74,
        "segura": 2.0,
        "hist": 57.6,
        "n": 172,
        "cruza": true,
        "cruza_segura": true
      },
      {
        "mercado": "over15+over05_local",
        "etiqueta": "Over 1.5 + Over 0.5 L",
        "cuota": 1.24,
        "justa": 1.27,
        "segura": 1.39,
        "hist": 78.6,
        "n": 182,
        "cruza": false,
        "cruza_segura": false
      },
      {
        "mercado": "over15+hcp3_visit",
        "etiqueta": "Over 1.5 + HCP +3 V",
        "cuota": 1.67,
        "justa": 1.55,
        "segura": 1.68,
        "hist": 64.5,
        "n": 375,
        "cruza": true,
        "cruza_segura": false
      },
      {
        "mercado": "do1x+under35",
        "etiqueta": "DO L o Empate + Under 3.5",
        "cuota": 1.67,
        "justa": 1.98,
        "segura": 2.24,
        "hist": 50.5,
        "n": 277,
        "cruza": false,
        "cruza_segura": false
      }
    ],
    "validadas": [
      {
        "mercado": "btts",
        "etiqueta": "BTTS",
        "tipo": "simple",
        "p": 0.5738,
        "cuota_justa": 1.7,
        "cuota_segura": 1.83,
        "acierto_hist": 58.7,
        "n_hist": 606,
        "cotizada": true
      },
      {
        "mercado": "over05_visit+hcp2_local",
        "etiqueta": "Over 0.5 V + HCP +2 L",
        "tipo": "COMBINADA",
        "p": 0.5702,
        "cuota_justa": 1.68,
        "cuota_segura": 1.8,
        "acierto_hist": 59.6,
        "n_hist": 582,
        "cotizada": false
      },
      {
        "mercado": "do1x+hcp3_visit",
        "etiqueta": "DO L o Empate + HCP +3 V",
        "tipo": "COMBINADA",
        "p": 0.6367,
        "cuota_justa": 1.54,
        "cuota_segura": 1.65,
        "acierto_hist": 65.1,
        "n_hist": 498,
        "cotizada": false
      },
      {
        "mercado": "over15+hcp3_visit",
        "etiqueta": "Over 1.5 + HCP +3 V",
        "tipo": "COMBINADA",
        "p": 0.6247,
        "cuota_justa": 1.55,
        "cuota_segura": 1.68,
        "acierto_hist": 64.5,
        "n_hist": 375,
        "cotizada": true
      },
      {
        "mercado": "over25",
        "etiqueta": "Over 2.5",
        "tipo": "simple",
        "p": 0.573,
        "cuota_justa": 1.82,
        "cuota_segura": 2.0,
        "acierto_hist": 55.1,
        "n_hist": 354,
        "cotizada": true
      },
      {
        "mercado": "under35",
        "etiqueta": "Under 3.5",
        "tipo": "simple",
        "p": 0.6561,
        "cuota_justa": 1.51,
        "cuota_segura": 1.64,
        "acierto_hist": 66.3,
        "n_hist": 341,
        "cotizada": true
      },
      {
        "mercado": "btts+hcp2_local",
        "etiqueta": "BTTS + HCP +2 L",
        "tipo": "COMBINADA",
        "p": 0.5175,
        "cuota_justa": 1.85,
        "cuota_segura": 2.05,
        "acierto_hist": 54.1,
        "n_hist": 338,
        "cotizada": false
      },
      {
        "mercado": "local_corners_equipo_over3.5",
        "etiqueta": "Athletic Club Corners Over 3.5",
        "tipo": "por equipo",
        "p": 0.6726,
        "cuota_justa": 1.44,
        "cuota_segura": 1.56,
        "acierto_hist": 69.2,
        "n_hist": 325,
        "cotizada": true
      },
      {
        "mercado": "under35+hcp2_local",
        "etiqueta": "Under 3.5 + HCP +2 L",
        "tipo": "COMBINADA",
        "p": 0.6202,
        "cuota_justa": 1.68,
        "cuota_segura": 1.86,
        "acierto_hist": 59.5,
        "n_hist": 301,
        "cotizada": false
      },
      {
        "mercado": "btts+local_remates_puerta_over2.5",
        "etiqueta": "BTTS + L Remates a puerta Over 2.5",
        "tipo": "COMBINADA",
        "p": 0.5382,
        "cuota_justa": 1.86,
        "cuota_segura": 2.08,
        "acierto_hist": 53.9,
        "n_hist": 297,
        "cotizada": false
      },
      {
        "mercado": "do1x+under35",
        "etiqueta": "DO L o Empate + Under 3.5",
        "tipo": "COMBINADA",
        "p": 0.5155,
        "cuota_justa": 1.98,
        "cuota_segura": 2.24,
        "acierto_hist": 50.5,
        "n_hist": 277,
        "cotizada": true
      },
      {
        "mercado": "local_remates_over9.5",
        "etiqueta": "Athletic Club Remates Over 9.5",
        "tipo": "por equipo",
        "p": 0.7685,
        "cuota_justa": 1.29,
        "cuota_segura": 1.39,
        "acierto_hist": 77.2,
        "n_hist": 268,
        "cotizada": false
      },
      {
        "mercado": "over25+hcp3_local",
        "etiqueta": "Over 2.5 + HCP +3 L",
        "tipo": "COMBINADA",
        "p": 0.5492,
        "cuota_justa": 1.89,
        "cuota_segura": 2.14,
        "acierto_hist": 52.9,
        "n_hist": 261,
        "cotizada": false
      },
      {
        "mercado": "over05_visit",
        "etiqueta": "Over 0.5 V",
        "tipo": "simple",
        "p": 0.6383,
        "cuota_justa": 1.59,
        "cuota_segura": 1.77,
        "acierto_hist": 62.9,
        "n_hist": 224,
        "cotizada": true
      },
      {
        "mercado": "local_remates_puerta_over3.5",
        "etiqueta": "Athletic Club Remates a puerta Over 3.5",
        "tipo": "por equipo",
        "p": 0.7003,
        "cuota_justa": 1.37,
        "cuota_segura": 1.51,
        "acierto_hist": 72.8,
        "n_hist": 206,
        "cotizada": false
      },
      {
        "mercado": "local_remates_over8.5+local_remates_puerta_over2.5",
        "etiqueta": "L Remates Over 8.5 + L Remates a puerta Over 2.5",
        "tipo": "COMBINADA",
        "p": 0.7764,
        "cuota_justa": 1.33,
        "cuota_segura": 1.45,
        "acierto_hist": 75.2,
        "n_hist": 202,
        "cotizada": false
      },
      {
        "mercado": "local_corners_equipo_over2.5+local_remates_over9.5",
        "etiqueta": "L Corners Over 2.5 + L Remates Over 9.5",
        "tipo": "COMBINADA",
        "p": 0.675,
        "cuota_justa": 1.52,
        "cuota_segura": 1.7,
        "acierto_hist": 65.8,
        "n_hist": 199,
        "cotizada": false
      },
      {
        "mercado": "local_remates_over11.5",
        "etiqueta": "Athletic Club Remates Over 11.5",
        "tipo": "por equipo",
        "p": 0.6023,
        "cuota_justa": 1.67,
        "cuota_segura": 1.89,
        "acierto_hist": 59.8,
        "n_hist": 199,
        "cotizada": false
      },
      {
        "mercado": "local_remates_over11.5+local_remates_puerta_over3.5",
        "etiqueta": "L Remates Over 11.5 + L Remates a puerta Over 3.5",
        "tipo": "COMBINADA",
        "p": 0.5427,
        "cuota_justa": 1.95,
        "cuota_segura": 2.26,
        "acierto_hist": 51.3,
        "n_hist": 191,
        "cotizada": false
      },
      {
        "mercado": "local_remates_over9.5+local_remates_puerta_over2.5",
        "etiqueta": "L Remates Over 9.5 + L Remates a puerta Over 2.5",
        "tipo": "COMBINADA",
        "p": 0.7224,
        "cuota_justa": 1.35,
        "cuota_segura": 1.48,
        "acierto_hist": 74.3,
        "n_hist": 191,
        "cotizada": false
      },
      {
        "mercado": "local_remates_puerta_over3.5+over15",
        "etiqueta": "L Remates a puerta Over 3.5 + Over 1.5",
        "tipo": "COMBINADA",
        "p": 0.61,
        "cuota_justa": 1.61,
        "cuota_segura": 1.82,
        "acierto_hist": 62.1,
        "n_hist": 190,
        "cotizada": false
      },
      {
        "mercado": "local_corners_equipo_over3.5+local_remates_over9.5",
        "etiqueta": "L Corners Over 3.5 + L Remates Over 9.5",
        "tipo": "COMBINADA",
        "p": 0.5711,
        "cuota_justa": 1.69,
        "cuota_segura": 1.93,
        "acierto_hist": 59.0,
        "n_hist": 188,
        "cotizada": false
      },
      {
        "mercado": "local_remates_puerta_over2.5+over05_local",
        "etiqueta": "L Remates a puerta Over 2.5 + Over 0.5 L",
        "tipo": "COMBINADA",
        "p": 0.7871,
        "cuota_justa": 1.33,
        "cuota_segura": 1.46,
        "acierto_hist": 75.0,
        "n_hist": 184,
        "cotizada": false
      },
      {
        "mercado": "local_remates_puerta_over4.5",
        "etiqueta": "Athletic Club Remates a puerta Over 4.5",
        "tipo": "por equipo",
        "p": 0.5273,
        "cuota_justa": 1.93,
        "cuota_segura": 2.24,
        "acierto_hist": 51.9,
        "n_hist": 183,
        "cotizada": false
      },
      {
        "mercado": "over15+over05_local",
        "etiqueta": "Over 1.5 + Over 0.5 L",
        "tipo": "COMBINADA",
        "p": 0.7561,
        "cuota_justa": 1.27,
        "cuota_segura": 1.39,
        "acierto_hist": 78.6,
        "n_hist": 182,
        "cotizada": true
      },
      {
        "mercado": "visit_remates_over10.5",
        "etiqueta": "Elche Remates Over 10.5",
        "tipo": "por equipo",
        "p": 0.5474,
        "cuota_justa": 1.96,
        "cuota_segura": 2.28,
        "acierto_hist": 51.1,
        "n_hist": 178,
        "cotizada": false
      },
      {
        "mercado": "over05_visit+visit_remates_puerta_over2.5",
        "etiqueta": "Over 0.5 V + V Remates a puerta Over 2.5",
        "tipo": "COMBINADA",
        "p": 0.5838,
        "cuota_justa": 1.78,
        "cuota_segura": 2.06,
        "acierto_hist": 56.1,
        "n_hist": 173,
        "cotizada": false
      },
      {
        "mercado": "visit_remates_puerta_over3.5",
        "etiqueta": "Elche Remates a puerta Over 3.5",
        "tipo": "por equipo",
        "p": 0.5752,
        "cuota_justa": 1.74,
        "cuota_segura": 2.0,
        "acierto_hist": 57.6,
        "n_hist": 172,
        "cotizada": true
      },
      {
        "mercado": "local_corners_equipo_over3.5+local_remates_over10.5",
        "etiqueta": "L Corners Over 3.5 + L Remates Over 10.5",
        "tipo": "COMBINADA",
        "p": 0.5309,
        "cuota_justa": 1.95,
        "cuota_segura": 2.29,
        "acierto_hist": 51.2,
        "n_hist": 172,
        "cotizada": false
      },
      {
        "mercado": "over15+hcp2_local",
        "etiqueta": "Over 1.5 + HCP +2 L",
        "tipo": "COMBINADA",
        "p": 0.7267,
        "cuota_justa": 1.34,
        "cuota_segura": 1.47,
        "acierto_hist": 74.9,
        "n_hist": 171,
        "cotizada": false
      },
      {
        "mercado": "local_corners_equipo_over2.5+local_remates_over11.5",
        "etiqueta": "L Corners Over 2.5 + L Remates Over 11.5",
        "tipo": "COMBINADA",
        "p": 0.5351,
        "cuota_justa": 2.0,
        "cuota_segura": 2.35,
        "acierto_hist": 50.0,
        "n_hist": 168,
        "cotizada": false
      },
      {
        "mercado": "visit_corners_equipo_over3.5",
        "etiqueta": "Elche Corners Over 3.5",
        "tipo": "por equipo",
        "p": 0.6879,
        "cuota_justa": 1.49,
        "cuota_segura": 1.68,
        "acierto_hist": 67.3,
        "n_hist": 159,
        "cotizada": true
      },
      {
        "mercado": "hcp2_local+local_remates_puerta_over3.5",
        "etiqueta": "HCP +2 L + L Remates a puerta Over 3.5",
        "tipo": "COMBINADA",
        "p": 0.6792,
        "cuota_justa": 1.5,
        "cuota_segura": 1.7,
        "acierto_hist": 66.5,
        "n_hist": 155,
        "cotizada": false
      }
    ]
  },
  {
    "id": "003",
    "fecha": "2026-09-12",
    "jornada": 5,
    "liga": "SP1",
    "partido": "Racing Santander vs Alaves",
    "lambda_forma_l": 1.1833,
    "lambda_forma_v": 1.2997,
    "lambda_reg_l": 1.249,
    "lambda_reg_v": 0.9386,
    "lambda_base_l": 1.2293,
    "lambda_base_v": 1.0469,
    "lambda_final_l": 1.2475,
    "lambda_final_v": 1.0287,
    "lambda_shadow_l": 1.1851,
    "lambda_shadow_v": 0.9876,
    "lambda_corners": null,
    "ratio": 1.2126956352678138,
    "visit_dominante": "False",
    "variables_activas": "V#2(L:0.95) - V#4(V:0.96)",
    "variables": {
      "v1": {
        "factor_local": 1.0,
        "factor_visit": 1.0,
        "activa": false,
        "activa_local": false,
        "activa_visit": false,
        "detalle_local": "--",
        "detalle_visit": "--",
        "detalle": "Ambos necesitan >=20 PJ (local:4, visit:4)"
      },
      "v2": {
        "factor_local": 0.95,
        "factor_visit": 1.0,
        "activa_local": true,
        "activa_visit": false,
        "detalle_local": "Rank 13, margen 2pts sobre zona desc",
        "detalle_visit": "Rank 2, margen 8pts -- fuera de riesgo"
      },
      "v3": {
        "factor_local": 1.0,
        "activa": false,
        "n_partidos": 2,
        "detalle": "Solo 2 partidos como local (min 10)"
      },
      "v4": {
        "factor_local": 1.0,
        "factor_visit": 0.96,
        "activa_local": false,
        "activa_visit": true,
        "bajas_local": 1,
        "bajas_visit": 2
      },
      "v5": {
        "factor_local": 1.0,
        "factor_visit": 1.0,
        "activa_local": false,
        "activa_visit": false
      },
      "v6": {
        "factor_local": 1.0,
        "factor_visit": 1.0,
        "activa": false
      },
      "v7": {
        "skip": false,
        "activa_local": false,
        "activa_visit": false,
        "detalle": "Sin DT nuevo"
      },
      "v8": {
        "activa": false,
        "anulado_derby": false,
        "detalle": "Inactiva"
      }
    },
    "confianza": "ALTA",
    "notas": "",
    "resultado_partido": null,
    "goles_esperados": "2.28",
    "apuestas": [
      {
        "tipo": "PICK",
        "mercado": "do1x",
        "linea": null,
        "etiqueta": "DO Racing Santander o Empate",
        "cuota": 1.45,
        "prob": 71.1,
        "ev_pct": 3.1,
        "estado": "PENDIENTE",
        "pl": null,
        "cuota_justa": 1.42,
        "cuota_segura": 1.57,
        "acierto_hist": 70.6,
        "n_hist": 194
      },
      {
        "tipo": "PICK",
        "mercado": "under35",
        "linea": null,
        "etiqueta": "Under 3.5",
        "cuota": 1.44,
        "prob": 80.4,
        "ev_pct": 15.8,
        "estado": "PENDIENTE",
        "pl": null
      },
      {
        "tipo": "COMBO",
        "mercado": "under35+hcp2_local",
        "etiqueta": "Under 3.5 + HCP +2 L",
        "cuota": 1.57,
        "prob": 73.1,
        "ev_pct": 14.8,
        "estado": "PENDIENTE",
        "pl": null,
        "patas": [
          "under35",
          "hcp2_local"
        ],
        "promovida_combinada": true,
        "nivel_cruce": "segura",
        "cuota_justa": 1.37,
        "cuota_segura": 1.5,
        "acierto_hist": 73.2,
        "n_hist": 205
      }
    ],
    "watchlist": [
      {
        "mercado": "victoria_local",
        "linea": null,
        "etiqueta": "Victoria Racing Santander",
        "cuota": 2.42,
        "prob": 41.2,
        "ev_pct": -0.3
      },
      {
        "mercado": "empate",
        "linea": null,
        "etiqueta": "Empate",
        "cuota": 3.5,
        "prob": 31.8,
        "ev_pct": 11.3,
        "regla_1x2_no_pick": true
      },
      {
        "mercado": "hcp2_des",
        "linea": null,
        "etiqueta": "HCP +2 Alaves",
        "cuota": 1.2,
        "prob": 81.7,
        "ev_pct": -2.0
      },
      {
        "mercado": "hcp3_des",
        "linea": null,
        "etiqueta": "HCP +3 Alaves",
        "cuota": 1.06,
        "prob": 93.7,
        "ev_pct": -0.7
      },
      {
        "mercado": "visit_remates_puerta",
        "linea": 3.5,
        "etiqueta": "Alaves Remates a puerta Over 3.5",
        "cuota": 1.57,
        "prob": 58.1,
        "ev_pct": -8.8,
        "tipo": "POR_EQUIPO",
        "cuota_justa": 1.74,
        "cuota_segura": 2.0,
        "acierto_hist": 57.6,
        "n_hist": 172
      },
      {
        "mercado": "do1x+hcp3_visit",
        "linea": null,
        "etiqueta": "DO L o Empate + HCP +3 V",
        "cuota": 1.57,
        "prob": 63.3,
        "ev_pct": -0.6,
        "tipo": "COMBINADA",
        "patas": [
          "do1x",
          "hcp3_visit"
        ],
        "lift": 0.962,
        "cuota_justa": 1.54,
        "cuota_segura": 1.65,
        "acierto_hist": 65.1,
        "n_hist": 498
      },
      {
        "mercado": "over15+hcp3_visit",
        "linea": null,
        "etiqueta": "Over 1.5 + HCP +3 V",
        "cuota": 1.36,
        "prob": 60.1,
        "ev_pct": -18.3,
        "tipo": "COMBINADA",
        "patas": [
          "over15",
          "hcp3_visit"
        ],
        "lift": 0.962,
        "cuota_justa": 1.55,
        "cuota_segura": 1.68,
        "acierto_hist": 64.5,
        "n_hist": 375
      },
      {
        "mercado": "under35+hcp2_visit",
        "linea": null,
        "etiqueta": "Under 3.5 + HCP +2 V",
        "cuota": 1.65,
        "prob": 69.1,
        "ev_pct": 14.0,
        "tipo": "COMBINADA",
        "patas": [
          "under35",
          "hcp2_visit"
        ],
        "lift": 1.106,
        "cuota_justa": 1.48,
        "cuota_segura": 1.62,
        "acierto_hist": 67.7,
        "n_hist": 269
      },
      {
        "mercado": "do1x+over05_local",
        "linea": null,
        "etiqueta": "DO L o Empate + Over 0.5 L",
        "cuota": 1.55,
        "prob": 59.3,
        "ev_pct": -8.1,
        "tipo": "COMBINADA",
        "patas": [
          "do1x",
          "over05_local"
        ],
        "lift": 1.189,
        "cuota_justa": 1.69,
        "cuota_segura": 1.93,
        "acierto_hist": 59.3,
        "n_hist": 172
      },
      {
        "mercado": "over15+over05_local",
        "linea": null,
        "etiqueta": "Over 1.5 + Over 0.5 L",
        "cuota": 1.37,
        "prob": 58.5,
        "ev_pct": -19.9,
        "tipo": "COMBINADA",
        "patas": [
          "over15",
          "over05_local"
        ],
        "lift": 1.158,
        "cuota_justa": 1.75,
        "cuota_segura": 1.98,
        "acierto_hist": 57.1,
        "n_hist": 210
      },
      {
        "mercado": "under25",
        "linea": null,
        "etiqueta": "Under 2.5",
        "cuota": 2.07,
        "prob": 57.8,
        "ev_pct": 19.6,
        "regla_unicidad_totales": "cede ante under35 (score EV/prob 12.7)"
      },
      {
        "mercado": "under45",
        "linea": null,
        "etiqueta": "Under 4.5",
        "cuota": 1.17,
        "prob": 91.9,
        "ev_pct": 7.5,
        "regla_unicidad_totales": "cede ante under35 (score EV/prob 12.7)"
      }
    ],
    "mercados_snapshot": {
      "victoria_local": 41.2,
      "empate": 31.8,
      "victoria_visit": 28.9,
      "do1x": 71.1,
      "dox2": 58.8,
      "over15": 70.5,
      "over25": 42.2,
      "under25": 57.8,
      "over35": 19.6,
      "under35": 80.4,
      "under45": 91.9,
      "btts": 52.0,
      "over05_local": 72.9,
      "over05_visit": 64.2,
      "hcp2_des": 81.7,
      "hcp3_des": 93.7,
      "local_remates_over7.5": 83.5,
      "local_remates_over8.5": 75.8,
      "local_remates_over9.5": 67.0,
      "local_remates_over10.5": 57.6,
      "local_remates_over11.5": 48.1,
      "local_remates_over12.5": 39.1,
      "local_remates_over13.5": 31.0,
      "local_remates_over14.5": 23.9,
      "local_remates_over15.5": 18.0,
      "local_remates_puerta_over1.5": 88.9,
      "local_remates_puerta_over2.5": 73.1,
      "local_remates_puerta_over3.5": 53.6,
      "local_remates_puerta_over4.5": 35.0,
      "local_remates_puerta_over5.5": 20.5,
      "local_remates_puerta_over6.5": 10.9,
      "local_corners_equipo_over2.5": 85.8,
      "local_corners_equipo_over3.5": 73.4,
      "local_corners_equipo_over4.5": 59.2,
      "local_corners_equipo_over5.5": 44.9,
      "local_corners_equipo_over6.5": 32.4,
      "local_corners_equipo_over7.5": 22.2,
      "visit_remates_over7.5": 89.4,
      "visit_remates_over8.5": 83.7,
      "visit_remates_over9.5": 76.7,
      "visit_remates_over10.5": 68.6,
      "visit_remates_over11.5": 60.0,
      "visit_remates_over12.5": 51.2,
      "visit_remates_over13.5": 42.6,
      "visit_remates_over14.5": 34.7,
      "visit_remates_over15.5": 27.6,
      "visit_remates_puerta_over1.5": 90.7,
      "visit_remates_puerta_over2.5": 76.6,
      "visit_remates_puerta_over3.5": 58.1,
      "visit_remates_puerta_over4.5": 39.5,
      "visit_remates_puerta_over5.5": 24.2,
      "visit_remates_puerta_over6.5": 13.5,
      "visit_corners_equipo_over2.5": 85.9,
      "visit_corners_equipo_over3.5": 73.6,
      "visit_corners_equipo_over4.5": 59.3,
      "visit_corners_equipo_over5.5": 45.1,
      "visit_corners_equipo_over6.5": 32.5,
      "visit_corners_equipo_over7.5": 22.3
    },
    "cruces_validados": [
      {
        "mercado": "do1x",
        "etiqueta": "DO L o Empate",
        "cuota": 1.45,
        "justa": 1.42,
        "segura": 1.57,
        "hist": 70.6,
        "n": 194,
        "cruza": true,
        "cruza_segura": false
      },
      {
        "mercado": "over05_local",
        "etiqueta": "Over 0.5 L",
        "cuota": 1.24,
        "justa": 1.38,
        "segura": 1.51,
        "hist": 72.3,
        "n": 238,
        "cruza": false,
        "cruza_segura": false
      },
      {
        "mercado": "over05_visit",
        "etiqueta": "Over 0.5 V",
        "cuota": 1.28,
        "justa": 1.59,
        "segura": 1.77,
        "hist": 62.9,
        "n": 224,
        "cruza": false,
        "cruza_segura": false
      },
      {
        "mercado": "visit_remates_puerta_over3.5",
        "etiqueta": "Alaves Remates a puerta Over 3.5",
        "cuota": 1.57,
        "justa": 1.74,
        "segura": 2.0,
        "hist": 57.6,
        "n": 172,
        "cruza": false,
        "cruza_segura": false
      },
      {
        "mercado": "do1x+hcp3_visit",
        "etiqueta": "DO L o Empate + HCP +3 V",
        "cuota": 1.57,
        "justa": 1.54,
        "segura": 1.65,
        "hist": 65.1,
        "n": 498,
        "cruza": true,
        "cruza_segura": false
      },
      {
        "mercado": "over15+hcp3_visit",
        "etiqueta": "Over 1.5 + HCP +3 V",
        "cuota": 1.36,
        "justa": 1.55,
        "segura": 1.68,
        "hist": 64.5,
        "n": 375,
        "cruza": false,
        "cruza_segura": false
      },
      {
        "mercado": "under35+hcp2_visit",
        "etiqueta": "Under 3.5 + HCP +2 V",
        "cuota": 1.65,
        "justa": 1.48,
        "segura": 1.62,
        "hist": 67.7,
        "n": 269,
        "cruza": true,
        "cruza_segura": true
      },
      {
        "mercado": "under35+hcp2_local",
        "etiqueta": "Under 3.5 + HCP +2 L",
        "cuota": 1.57,
        "justa": 1.37,
        "segura": 1.5,
        "hist": 73.2,
        "n": 205,
        "cruza": true,
        "cruza_segura": true
      },
      {
        "mercado": "do1x+over05_local",
        "etiqueta": "DO L o Empate + Over 0.5 L",
        "cuota": 1.55,
        "justa": 1.69,
        "segura": 1.93,
        "hist": 59.3,
        "n": 172,
        "cruza": false,
        "cruza_segura": false
      },
      {
        "mercado": "over15+over05_local",
        "etiqueta": "Over 1.5 + Over 0.5 L",
        "cuota": 1.37,
        "justa": 1.75,
        "segura": 1.98,
        "hist": 57.1,
        "n": 210,
        "cruza": false,
        "cruza_segura": false
      }
    ],
    "validadas": [
      {
        "mercado": "do1x+hcp3_visit",
        "etiqueta": "DO L o Empate + HCP +3 V",
        "tipo": "COMBINADA",
        "p": 0.6331,
        "cuota_justa": 1.54,
        "cuota_segura": 1.65,
        "acierto_hist": 65.1,
        "n_hist": 498,
        "cotizada": true
      },
      {
        "mercado": "over15+hcp3_visit",
        "etiqueta": "Over 1.5 + HCP +3 V",
        "tipo": "COMBINADA",
        "p": 0.601,
        "cuota_justa": 1.55,
        "cuota_segura": 1.68,
        "acierto_hist": 64.5,
        "n_hist": 375,
        "cotizada": true
      },
      {
        "mercado": "over15+visit_remates_puerta_over2.5",
        "etiqueta": "Over 1.5 + V Remates a puerta Over 2.5",
        "tipo": "COMBINADA",
        "p": 0.5979,
        "cuota_justa": 1.73,
        "cuota_segura": 1.92,
        "acierto_hist": 57.7,
        "n_hist": 310,
        "cotizada": false
      },
      {
        "mercado": "under45+over05_visit",
        "etiqueta": "Under 4.5 + Over 0.5 V",
        "tipo": "COMBINADA",
        "p": 0.5648,
        "cuota_justa": 1.66,
        "cuota_segura": 1.83,
        "acierto_hist": 60.1,
        "n_hist": 308,
        "cotizada": false
      },
      {
        "mercado": "dox2+hcp3_local",
        "etiqueta": "DO Empate o V + HCP +3 L",
        "tipo": "COMBINADA",
        "p": 0.5544,
        "cuota_justa": 1.72,
        "cuota_segura": 1.91,
        "acierto_hist": 58.1,
        "n_hist": 296,
        "cotizada": false
      },
      {
        "mercado": "local_corners_equipo_over4.5",
        "etiqueta": "Racing Santander Corners Over 4.5",
        "tipo": "por equipo",
        "p": 0.5915,
        "cuota_justa": 1.69,
        "cuota_segura": 1.88,
        "acierto_hist": 59.1,
        "n_hist": 286,
        "cotizada": false
      },
      {
        "mercado": "over15+hcp3_local",
        "etiqueta": "Over 1.5 + HCP +3 L",
        "tipo": "COMBINADA",
        "p": 0.6306,
        "cuota_justa": 1.56,
        "cuota_segura": 1.71,
        "acierto_hist": 64.1,
        "n_hist": 284,
        "cotizada": false
      },
      {
        "mercado": "under35+hcp2_visit",
        "etiqueta": "Under 3.5 + HCP +2 V",
        "tipo": "COMBINADA",
        "p": 0.6911,
        "cuota_justa": 1.48,
        "cuota_segura": 1.62,
        "acierto_hist": 67.7,
        "n_hist": 269,
        "cotizada": true
      },
      {
        "mercado": "over05_local",
        "etiqueta": "Over 0.5 L",
        "tipo": "simple",
        "p": 0.7291,
        "cuota_justa": 1.38,
        "cuota_segura": 1.51,
        "acierto_hist": 72.3,
        "n_hist": 238,
        "cotizada": true
      },
      {
        "mercado": "dox2+under45",
        "etiqueta": "DO Empate o V + Under 4.5",
        "tipo": "COMBINADA",
        "p": 0.5511,
        "cuota_justa": 1.67,
        "cuota_segura": 1.88,
        "acierto_hist": 59.7,
        "n_hist": 226,
        "cotizada": false
      },
      {
        "mercado": "under25+hcp2_local",
        "etiqueta": "Under 2.5 + HCP +2 L",
        "tipo": "COMBINADA",
        "p": 0.548,
        "cuota_justa": 1.97,
        "cuota_segura": 2.26,
        "acierto_hist": 50.7,
        "n_hist": 225,
        "cotizada": false
      },
      {
        "mercado": "over05_visit",
        "etiqueta": "Over 0.5 V",
        "tipo": "simple",
        "p": 0.6425,
        "cuota_justa": 1.59,
        "cuota_segura": 1.77,
        "acierto_hist": 62.9,
        "n_hist": 224,
        "cotizada": true
      },
      {
        "mercado": "over15+over05_local",
        "etiqueta": "Over 1.5 + Over 0.5 L",
        "tipo": "COMBINADA",
        "p": 0.5847,
        "cuota_justa": 1.75,
        "cuota_segura": 1.98,
        "acierto_hist": 57.1,
        "n_hist": 210,
        "cotizada": true
      },
      {
        "mercado": "under35+hcp2_local",
        "etiqueta": "Under 3.5 + HCP +2 L",
        "tipo": "COMBINADA",
        "p": 0.7312,
        "cuota_justa": 1.37,
        "cuota_segura": 1.5,
        "acierto_hist": 73.2,
        "n_hist": 205,
        "cotizada": true
      },
      {
        "mercado": "do1x",
        "etiqueta": "DO L o Empate",
        "tipo": "simple",
        "p": 0.7111,
        "cuota_justa": 1.42,
        "cuota_segura": 1.57,
        "acierto_hist": 70.6,
        "n_hist": 194,
        "cotizada": true
      },
      {
        "mercado": "local_remates_puerta_over2.5",
        "etiqueta": "Racing Santander Remates a puerta Over 2.5",
        "tipo": "por equipo",
        "p": 0.731,
        "cuota_justa": 1.39,
        "cuota_segura": 1.53,
        "acierto_hist": 72.0,
        "n_hist": 189,
        "cotizada": false
      },
      {
        "mercado": "visit_remates_over7.5+visit_remates_puerta_over2.5",
        "etiqueta": "V Remates Over 7.5 + V Remates a puerta Over 2.5",
        "tipo": "COMBINADA",
        "p": 0.7586,
        "cuota_justa": 1.35,
        "cuota_segura": 1.49,
        "acierto_hist": 74.1,
        "n_hist": 185,
        "cotizada": false
      },
      {
        "mercado": "local_remates_over8.5",
        "etiqueta": "Racing Santander Remates Over 8.5",
        "tipo": "por equipo",
        "p": 0.7582,
        "cuota_justa": 1.32,
        "cuota_segura": 1.44,
        "acierto_hist": 76.0,
        "n_hist": 183,
        "cotizada": false
      },
      {
        "mercado": "over05_visit+visit_remates_puerta_over2.5",
        "etiqueta": "Over 0.5 V + V Remates a puerta Over 2.5",
        "tipo": "COMBINADA",
        "p": 0.5909,
        "cuota_justa": 1.78,
        "cuota_segura": 2.06,
        "acierto_hist": 56.1,
        "n_hist": 173,
        "cotizada": false
      },
      {
        "mercado": "visit_remates_puerta_over3.5",
        "etiqueta": "Alaves Remates a puerta Over 3.5",
        "tipo": "por equipo",
        "p": 0.5809,
        "cuota_justa": 1.74,
        "cuota_segura": 2.0,
        "acierto_hist": 57.6,
        "n_hist": 172,
        "cotizada": true
      },
      {
        "mercado": "visit_remates_over8.5+visit_remates_puerta_over3.5",
        "etiqueta": "V Remates Over 8.5 + V Remates a puerta Over 3.5",
        "tipo": "COMBINADA",
        "p": 0.5905,
        "cuota_justa": 1.77,
        "cuota_segura": 2.04,
        "acierto_hist": 56.4,
        "n_hist": 172,
        "cotizada": false
      },
      {
        "mercado": "do1x+over05_local",
        "etiqueta": "DO L o Empate + Over 0.5 L",
        "tipo": "COMBINADA",
        "p": 0.5931,
        "cuota_justa": 1.69,
        "cuota_segura": 1.93,
        "acierto_hist": 59.3,
        "n_hist": 172,
        "cotizada": true
      },
      {
        "mercado": "local_remates_puerta_over2.5+over05_local",
        "etiqueta": "L Remates a puerta Over 2.5 + Over 0.5 L",
        "tipo": "COMBINADA",
        "p": 0.5983,
        "cuota_justa": 1.82,
        "cuota_segura": 2.1,
        "acierto_hist": 55.1,
        "n_hist": 167,
        "cotizada": false
      },
      {
        "mercado": "under25+hcp2_visit",
        "etiqueta": "Under 2.5 + HCP +2 V",
        "tipo": "COMBINADA",
        "p": 0.5225,
        "cuota_justa": 1.99,
        "cuota_segura": 2.34,
        "acierto_hist": 50.3,
        "n_hist": 163,
        "cotizada": false
      },
      {
        "mercado": "visit_remates_over9.5+visit_remates_puerta_over3.5",
        "etiqueta": "V Remates Over 9.5 + V Remates a puerta Over 3.5",
        "tipo": "COMBINADA",
        "p": 0.5679,
        "cuota_justa": 1.75,
        "cuota_segura": 2.02,
        "acierto_hist": 57.1,
        "n_hist": 161,
        "cotizada": false
      },
      {
        "mercado": "local_corners_equipo_over3.5+local_remates_over8.5",
        "etiqueta": "L Corners Over 3.5 + L Remates Over 8.5",
        "tipo": "COMBINADA",
        "p": 0.5971,
        "cuota_justa": 1.67,
        "cuota_segura": 1.92,
        "acierto_hist": 59.7,
        "n_hist": 159,
        "cotizada": false
      },
      {
        "mercado": "local_corners_equipo_over3.5+local_remates_over9.5",
        "etiqueta": "L Corners Over 3.5 + L Remates Over 9.5",
        "tipo": "COMBINADA",
        "p": 0.5436,
        "cuota_justa": 1.86,
        "cuota_segura": 2.17,
        "acierto_hist": 53.8,
        "n_hist": 156,
        "cotizada": false
      },
      {
        "mercado": "local_remates_puerta_over3.5",
        "etiqueta": "Racing Santander Remates a puerta Over 3.5",
        "tipo": "por equipo",
        "p": 0.5356,
        "cuota_justa": 1.88,
        "cuota_segura": 2.2,
        "acierto_hist": 53.3,
        "n_hist": 152,
        "cotizada": false
      }
    ]
  },
  {
    "id": "004",
    "fecha": "2026-09-12",
    "jornada": 5,
    "liga": "SP1",
    "partido": "Real Madrid vs Rayo Vallecano",
    "lambda_forma_l": 2.6183,
    "lambda_forma_v": 0.9232,
    "lambda_reg_l": 2.1914,
    "lambda_reg_v": 0.9781,
    "lambda_base_l": 2.3195,
    "lambda_base_v": 0.9616,
    "lambda_final_l": 2.4553,
    "lambda_final_v": 0.8258,
    "lambda_shadow_l": 2.4113,
    "lambda_shadow_v": 0.7061,
    "lambda_corners": 8.743,
    "ratio": 2.9732380721724385,
    "visit_dominante": "False",
    "variables_activas": "V#2(V:0.95) - V#3(L:1.10) - V#4(L:0.96) - V#4(V:0.90) - V#5(L:0.93)",
    "variables": {
      "v1": {
        "factor_local": 1.0,
        "factor_visit": 1.0,
        "activa": false,
        "activa_local": false,
        "activa_visit": false,
        "detalle_local": "--",
        "detalle_visit": "--",
        "detalle": "Ambos necesitan >=20 PJ (local:4, visit:4)"
      },
      "v2": {
        "factor_local": 1.0,
        "factor_visit": 0.95,
        "activa_local": false,
        "activa_visit": true,
        "detalle_local": "Rank 3, margen 7pts -- fuera de riesgo",
        "detalle_visit": "Rank 14, margen 2pts sobre zona desc"
      },
      "v3": {
        "factor_local": 1.1,
        "activa": true,
        "n_partidos": 20,
        "GpG_casa": 2.6,
        "GpG_liga": 1.5,
        "hs": 1.1,
        "muestra_completa": true,
        "detalle": "hs=+1.10 (20 ptdos)"
      },
      "v4": {
        "factor_local": 0.96,
        "factor_visit": 0.9,
        "activa_local": true,
        "activa_visit": true,
        "bajas_local": 3,
        "bajas_visit": 8
      },
      "v5": {
        "factor_local": 0.93,
        "factor_visit": 1.0,
        "activa_local": true,
        "activa_visit": false
      },
      "v6": {
        "factor_local": 1.0,
        "factor_visit": 1.0,
        "activa": false
      },
      "v7": {
        "skip": false,
        "activa_local": false,
        "activa_visit": false,
        "detalle": "Sin DT nuevo"
      },
      "v8": {
        "activa": true,
        "anulado_derby": false,
        "detalle": "ACTIVA -- copa <=5 dias"
      }
    },
    "confianza": "ALTA",
    "notas": "",
    "resultado_partido": null,
    "goles_esperados": "3.28",
    "apuestas": [
      {
        "tipo": "PICK",
        "mercado": "under35",
        "linea": null,
        "etiqueta": "Under 3.5",
        "cuota": 2.15,
        "prob": 58.5,
        "ev_pct": 25.8,
        "estado": "PENDIENTE",
        "pl": null
      },
      {
        "tipo": "PICK",
        "mercado": "btts",
        "linea": null,
        "etiqueta": "BTTS",
        "cuota": 1.98,
        "prob": 55.4,
        "ev_pct": 9.7,
        "estado": "PENDIENTE",
        "pl": null,
        "cuota_justa": 1.7,
        "cuota_segura": 1.83,
        "acierto_hist": 58.7,
        "n_hist": 606
      },
      {
        "tipo": "PICK",
        "mercado": "over05_visit",
        "linea": null,
        "etiqueta": "Over 0.5 Rayo Vallecano",
        "cuota": 1.93,
        "prob": 56.2,
        "ev_pct": 8.5,
        "estado": "PENDIENTE",
        "pl": null
      },
      {
        "tipo": "COMBO",
        "mercado": "over15+visit_remates_puerta_over2.5",
        "etiqueta": "Over 1.5 + V Remates a puerta Over 2.5",
        "cuota": 2.18,
        "prob": 50.7,
        "ev_pct": 10.4,
        "estado": "PENDIENTE",
        "pl": null,
        "patas": [
          "over15",
          "visit_remates_puerta_over2.5"
        ],
        "promovida_combinada": true,
        "nivel_cruce": "segura",
        "cuota_justa": 1.91,
        "cuota_segura": 2.18,
        "acierto_hist": 52.5,
        "n_hist": 223
      }
    ],
    "watchlist": [
      {
        "mercado": "empate",
        "linea": null,
        "etiqueta": "Empate",
        "cuota": 8.5,
        "prob": 17.4,
        "ev_pct": 47.9,
        "regla_1x2_no_pick": true
      },
      {
        "mercado": "corners65",
        "linea": null,
        "etiqueta": "Over 6.5 corners",
        "cuota": 1.16,
        "prob": 82.3,
        "ev_pct": -4.5
      },
      {
        "mercado": "visit_corners_equipo",
        "linea": 2.5,
        "etiqueta": "Rayo Vallecano Corners equipo Over 2.5",
        "cuota": 1.35,
        "prob": 69.5,
        "ev_pct": -6.2,
        "tipo": "POR_EQUIPO",
        "cuota_justa": 1.47,
        "cuota_segura": 1.59,
        "acierto_hist": 68.0,
        "n_hist": 319
      },
      {
        "mercado": "local_corners_equipo",
        "linea": 5.5,
        "etiqueta": "Real Madrid Corners equipo Over 5.5",
        "cuota": 1.78,
        "prob": 81.3,
        "ev_pct": 44.7,
        "tipo": "POR_EQUIPO"
      },
      {
        "mercado": "visit_remates_puerta",
        "linea": 2.5,
        "etiqueta": "Rayo Vallecano Remates a puerta Over 2.5",
        "cuota": 2.12,
        "prob": 54.6,
        "ev_pct": 15.8,
        "tipo": "POR_EQUIPO"
      },
      {
        "mercado": "do1x+under35",
        "linea": null,
        "etiqueta": "DO L o Empate + Under 3.5",
        "cuota": 2.25,
        "prob": 50.6,
        "ev_pct": 13.8,
        "tipo": "COMBINADA",
        "patas": [
          "do1x",
          "under35"
        ],
        "lift": 1.009,
        "cuota_justa": 1.98,
        "cuota_segura": 2.24,
        "acierto_hist": 50.5,
        "n_hist": 277
      },
      {
        "mercado": "under25",
        "linea": null,
        "etiqueta": "Under 2.5",
        "cuota": 3.65,
        "prob": 36.6,
        "ev_pct": 33.6,
        "regla_unicidad_totales": "cede ante under35 (score EV/prob 15.1)"
      },
      {
        "mercado": "under45",
        "linea": null,
        "etiqueta": "Under 4.5",
        "cuota": 1.52,
        "prob": 76.6,
        "ev_pct": 16.4,
        "regla_unicidad_totales": "cede ante under35 (score EV/prob 15.1)"
      }
    ],
    "mercados_snapshot": {
      "victoria_local": 73.1,
      "empate": 17.4,
      "victoria_visit": 8.2,
      "do1x": 91.8,
      "dox2": 26.9,
      "over15": 84.2,
      "over25": 63.3,
      "under25": 36.6,
      "over35": 41.5,
      "under35": 58.5,
      "under45": 76.6,
      "btts": 55.4,
      "over05_local": 93.0,
      "over05_visit": 56.2,
      "hcp2_des": 49.2,
      "hcp3_des": 70.4,
      "corners65": 82.3,
      "local_remates_over7.5": 99.8,
      "local_remates_over8.5": 99.6,
      "local_remates_over9.5": 99.2,
      "local_remates_over10.5": 98.7,
      "local_remates_over11.5": 97.9,
      "local_remates_over12.5": 96.7,
      "local_remates_over13.5": 95.0,
      "local_remates_over14.5": 92.9,
      "local_remates_over15.5": 90.3,
      "local_remates_puerta_over1.5": 99.9,
      "local_remates_puerta_over2.5": 99.4,
      "local_remates_puerta_over3.5": 98.1,
      "local_remates_puerta_over4.5": 95.3,
      "local_remates_puerta_over5.5": 90.5,
      "local_remates_puerta_over6.5": 83.3,
      "local_corners_equipo_over2.5": 97.5,
      "local_corners_equipo_over3.5": 94.0,
      "local_corners_equipo_over4.5": 88.6,
      "local_corners_equipo_over5.5": 81.3,
      "local_corners_equipo_over6.5": 72.4,
      "local_corners_equipo_over7.5": 62.7,
      "visit_remates_over7.5": 57.4,
      "visit_remates_over8.5": 45.7,
      "visit_remates_over9.5": 34.9,
      "visit_remates_over10.5": 25.6,
      "visit_remates_over11.5": 18.1,
      "visit_remates_over12.5": 12.4,
      "visit_remates_over13.5": 8.2,
      "visit_remates_over14.5": 5.2,
      "visit_remates_over15.5": 3.2,
      "visit_remates_puerta_over1.5": 77.4,
      "visit_remates_puerta_over2.5": 54.6,
      "visit_remates_puerta_over3.5": 33.1,
      "visit_remates_puerta_over4.5": 17.4,
      "visit_remates_puerta_over5.5": 8.1,
      "visit_remates_puerta_over6.5": 3.4,
      "visit_corners_equipo_over2.5": 69.5,
      "visit_corners_equipo_over3.5": 51.2,
      "visit_corners_equipo_over4.5": 34.6,
      "visit_corners_equipo_over5.5": 21.7,
      "visit_corners_equipo_over6.5": 12.8,
      "visit_corners_equipo_over7.5": 7.1
    },
    "cruces_validados": [
      {
        "mercado": "over25",
        "etiqueta": "Over 2.5",
        "cuota": 1.29,
        "justa": 1.56,
        "segura": 1.74,
        "hist": 64.1,
        "n": 206,
        "cruza": false,
        "cruza_segura": false
      },
      {
        "mercado": "btts",
        "etiqueta": "BTTS",
        "cuota": 1.98,
        "justa": 1.7,
        "segura": 1.83,
        "hist": 58.7,
        "n": 606,
        "cruza": true,
        "cruza_segura": true
      },
      {
        "mercado": "visit_corners_equipo_over2.5",
        "etiqueta": "Rayo Vallecano Corners Over 2.5",
        "cuota": 1.35,
        "justa": 1.47,
        "segura": 1.59,
        "hist": 68.0,
        "n": 319,
        "cruza": false,
        "cruza_segura": false
      },
      {
        "mercado": "do1x+under35",
        "etiqueta": "DO L o Empate + Under 3.5",
        "cuota": 2.25,
        "justa": 1.98,
        "segura": 2.24,
        "hist": 50.5,
        "n": 277,
        "cruza": true,
        "cruza_segura": true
      },
      {
        "mercado": "over15+visit_remates_puerta_over2.5",
        "etiqueta": "Over 1.5 + V Remates a puerta Over 2.5",
        "cuota": 2.18,
        "justa": 1.91,
        "segura": 2.18,
        "hist": 52.5,
        "n": 223,
        "cruza": true,
        "cruza_segura": true
      }
    ],
    "validadas": [
      {
        "mercado": "btts",
        "etiqueta": "BTTS",
        "tipo": "simple",
        "p": 0.5537,
        "cuota_justa": 1.7,
        "cuota_segura": 1.83,
        "acierto_hist": 58.7,
        "n_hist": 606,
        "cotizada": true
      },
      {
        "mercado": "btts+local_remates_puerta_over2.5",
        "etiqueta": "BTTS + L Remates a puerta Over 2.5",
        "tipo": "COMBINADA",
        "p": 0.5902,
        "cuota_justa": 1.77,
        "cuota_segura": 1.94,
        "acierto_hist": 56.6,
        "n_hist": 362,
        "cotizada": false
      },
      {
        "mercado": "visit_corners_equipo_over2.5",
        "etiqueta": "Rayo Vallecano Corners Over 2.5",
        "tipo": "por equipo",
        "p": 0.6946,
        "cuota_justa": 1.47,
        "cuota_segura": 1.59,
        "acierto_hist": 68.0,
        "n_hist": 319,
        "cotizada": true
      },
      {
        "mercado": "do1x+under35",
        "etiqueta": "DO L o Empate + Under 3.5",
        "tipo": "COMBINADA",
        "p": 0.5057,
        "cuota_justa": 1.98,
        "cuota_segura": 2.24,
        "acierto_hist": 50.5,
        "n_hist": 277,
        "cotizada": true
      },
      {
        "mercado": "over15+visit_remates_puerta_over2.5",
        "etiqueta": "Over 1.5 + V Remates a puerta Over 2.5",
        "tipo": "COMBINADA",
        "p": 0.5066,
        "cuota_justa": 1.91,
        "cuota_segura": 2.18,
        "acierto_hist": 52.5,
        "n_hist": 223,
        "cotizada": true
      },
      {
        "mercado": "over25",
        "etiqueta": "Over 2.5",
        "tipo": "simple",
        "p": 0.6335,
        "cuota_justa": 1.56,
        "cuota_segura": 1.74,
        "acierto_hist": 64.1,
        "n_hist": 206,
        "cotizada": true
      }
    ]
  }
];
